name: Deploy Cloud Functions

on:
  push:
    branches:
      - '**'


jobs:
  list-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - FUNCTION_NAME: Task

          - FUNCTION_NAME: Gcp
            
          - FUNCTION_NAME: App
           
        include:
          - function:
              - FUNCTION_NAME: Task
            ONLY_FUNCTION: 'yes'

    steps:
     - name: check 
       run: echo ${{ matrix.ONLY_FUNCTION }}
     
