name: Deploy Cloud Functions

on:
  push:
    branches:
      - '**'
      
      
env:
   FUNCTION_NAMES: "item1,item2,item3"
jobs:
  matinput:
    runs-on: ubuntu-latest
    outputs:
      fun: ${{ steps.step1.outputs.fun }}
    steps:
      - name: Step 1
        id: step1
        run: echo "fun=${{ env.FUNCTION_NAMES }}" >> $GITHUB_ENV
  list-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - ${{ needs.job1.outputs.fun }}
          

   

    steps:
     - name: check 
       run: echo "hi"
     
