name: Deploy Cloud Functions

on:
  push:
    branches:
      - '**'


jobs:
  list-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - ${{ env.FUNCTION_NAMES }}

    env:
      FUNCTION_NAMES: "Task,Gcp,App"

    steps:
     - name: check 
       run: echo "hi"
     
