name: Deploy Cloud Functions

on:
  push:
    branches:
      - '**'


jobs:
  list-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - FUNCTION_NAME: Task
            ONLY_FUNCTION: 'yes'
          - FUNCTION_NAME: Gcp
            ONLY_FUNCTION: 'yes'
          - FUNCTION_NAME: App
            ONLY_FUNCTION: 'yes'

    steps:
     - name: check 
       if: contains(matrix.functions.*.ONLY_FUNCTION, 'yes')
       run: echo "true"
        
