name: Deploy Cloud Functions

on:
  push:
    branches:
      - '**'
      
      
env:
   FUNCTION_NAMES: "Task"

jobs:
  list-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - ${{ env.FUNCTION_NAMES }}

   

    steps:
     - name: check 
       run: echo "hi"
     
